name: wildai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: ^6.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  provider: ^6.1.5
  http: ^1.4.0
  flutter_cohere: ^0.0.2
  icons_launcher: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/ai/
    - assets/loader/

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
